database:
  host: 127.0.0.1
  username: root
  password: root
server:
  port: 9091
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://${database.host}:3306/SPONGE?useSSL=false
      username: ${database.username}
      password: ${database.password}
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 1000
      validation-query: SELECT 1
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
mybatis:
  mapper-locations: classpath:com/apr7/sponge/dao/mapping/*.xml
  type-handlers-package: com.apr7.sponge.utils.mybatis.typehandler